.TH "include/Engine.hpp" 3 "Mon Feb 13 2023" "Version 0.1" "ViolaoMagico" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Engine.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'MyStepper\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEngine\fP"
.br
.RI "A classe \fBEngine\fP corresponde a único um motor\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ViolaoMagico from the source code\&.
