.TH "include/EnginesSet.hpp" 3 "Mon Feb 13 2023" "Version 0.1" "ViolaoMagico" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/EnginesSet.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Engine\&.hpp'\fP
.br
\fC#include 'SDCard\&.hpp'\fP
.br
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br
\fC#include <Arduino\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEnginesSet\fP"
.br
.RI "A classe \fBEnginesSet\fP corresponde a um conjunto de motores\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBbuttonUp\fP   3"
.br
.ti -1c
.RI "#define \fBbuttonSelect\fP   16"
.br
.ti -1c
.RI "#define \fBbuttonDown\fP   17"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define buttonDown   17"

.SS "#define buttonSelect   16"

.SS "#define buttonUp   3"

.SH "Author"
.PP 
Generated automatically by Doxygen for ViolaoMagico from the source code\&.
