.TH "include/MyStepper.hpp" 3 "Mon Feb 13 2023" "Version 0.1" "ViolaoMagico" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/MyStepper.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <Arduino\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMyStepper\fP"
.br
.RI "A classe \fBMyStepper\fP é utilizada para controlar os motores de passo\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ViolaoMagico from the source code\&.
