.TH "include/SDCard.hpp" 3 "Mon Feb 13 2023" "Version 0.1" "ViolaoMagico" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/SDCard.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <SD\&.h>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSDCard\fP"
.br
.RI "A classe \fBSDCard\fP usada para gerenciar um objeto do tipo SD da biblioteca de SD para Arduino\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ViolaoMagico from the source code\&.
